---
title: "CBMC-Fish Price Monitoring"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
resource_files:
- .secrets/bb8565617b5e9996ff93e6d214ba7218_favoretto@uabcs.mx
---

```{r setup, include=FALSE}

options(
  # whenever there is one account token found, use the cached token
  gargle_oauth_email = TRUE,
  # specify auth tokens should be stored in a hidden directory ".secrets"
  gargle_oauth_cache = ".secrets"
)


library(shiny)
library(flexdashboard)
library(googlesheets4)
library(tidyverse)
library(patchwork)
library(plotly)
library(see)

table_tdr <- read_sheet("https://docs.google.com/spreadsheets/d/1j4vKm0Nv37np8Jucfom68pFP78w10BtuuzKXgslgsY4/edit?usp=sharing")


prices <- read_sheet("https://docs.google.com/spreadsheets/d/1hefULquuA_iiB1O5eIDJwCBubGTsPixmNBDJ-VNZNxU/edit?usp=sharing")

fish_shops <- read_sheet("https://docs.google.com/spreadsheets/d/1hefULquuA_iiB1O5eIDJwCBubGTsPixmNBDJ-VNZNxU/edit?usp=sharing", sheet = 2)



# sniim <- table_tdr %>% 
#           pivot_longer(SNIIM_Precio_en_Origen:Walmart) %>% 
#           filter(name == "SNIIM_Precio_en_Origen") %>% 
#           mutate(Price = as.numeric(value), Species_common_name = Productos, Type = "SNIIM") %>%
#           select(Month, Species_common_name, Type, Price) %>% 
#           group_by(Species_common_name, Month) %>% 
#           summarise(Price = mean(Price, na.rm = T))
  
sniim <- read_sheet("https://docs.google.com/spreadsheets/d/1kPJblWSQJ20M-L48sw35hpEuT1G6rjK64K2_ksAiZLg/edit?usp=sharing")

supermarkets <- table_tdr %>% 
          pivot_longer(SNIIM_Precio_en_Origen:Walmart) %>% 
          filter(name != "SNIIM_Precio_en_Origen") %>% 
          mutate(Price = as.numeric(value), Species_common_name = Productos, Type = "Super") %>%
          select(Month, Species_common_name, Type, Price) %>% 
          group_by(Species_common_name, Month) %>% 
          summarise(Price = mean(Price, na.rm = T))

mercados <- prices %>% 
          select(Month, Species_common_name, Consumer_price, Producer_price) %>% 
          pivot_longer(Consumer_price:Producer_price, values_to = "Price", names_to = "Type")


prices <- prices %>% 
          mutate(Date = as.Date(paste0(Year, "-", Month, "-", Day), "%Y-%m-%d")) %>% 
          select(Date, Species_common_name, Consumer_price, Producer_price) %>% 
          group_by(Date, Species_common_name) %>% 
          summarise(Consumer_price = mean(Consumer_price, na.rm = T),
                    Producer_price = mean(Producer_price, na.rm = T)) %>% 
          mutate(Price_differential = Consumer_price - Producer_price) 

```

City Markets
=====================================  

Column {.sidebar}
-----------------------------------------------------------------------

Fish price monitoring.

```{r}

selectInput("species", label = "Species:",
            choices = unique(prices$Species_common_name), selected = "Atún")

```

Column {data-width=300}
-----------------------------------------------------------------------

### Fish Consumer Price

```{r}
renderPlot({
  prices %>% 
          filter(Species_common_name == as.character(input$species)) %>% 
          ggplot(aes(x = Date, y = Consumer_price)) +
          geom_point(aes(x = Date, y = Consumer_price), col = "darkgreen") +
          geom_line(aes(x = Date, y = Consumer_price), col = "darkgreen") +
          labs(x = "Date", y = "Consumer price (MXN)", subtitle = "Consumer price is the sale price to the public") +
          facet_wrap(~Species_common_name, scales = "free_y") +
          theme_lucid() +
          theme(strip.text = element_text(size = 17))
})
```

### Fish Producer Price

```{r}
renderPlot({
  prices %>% 
          filter(Species_common_name == as.character(input$species)) %>% 
          ggplot(aes(x = Date, y = Producer_price)) +
          geom_point(aes(x = Date, y = Producer_price), col = "blue") +
          geom_line(aes(x = Date, y = Producer_price), col = "blue") +
          labs(x = "Date", y = "Producer price (MXN)", subtitle = "Producer price is the price fish stores purchase the product to middlemen/fishermen") +
          facet_wrap(~Species_common_name, scales = "free_y") +
          theme_lucid() +
          theme(strip.text = element_text(size = 17))
})
```

### Fish Price Differential

```{r}
renderPlot({
  prices %>% 
          filter(Species_common_name == as.character(input$species)) %>% 
          ggplot(aes(x = Date, y = Consumer_price)) +
          geom_point(aes(x = Date, y = Price_differential), col = "firebrick") +
          geom_line(aes(x = Date, y = Price_differential), col = "firebrick") +
          labs(x = "Date", y = "Price differential (MXN)", subtitle = "Price differential is the difference between consumer price and producer price") +
          facet_wrap(~Species_common_name, scales = "free_y") +
          theme_lucid() +
          theme(strip.text = element_text(size = 17))
})
```

Column {data-width=100}
-----------------------------------------------------------------------

### ""

Supermarkets
=====================================  
Column {.sidebar}
-----------------------------------------------------------------------

Fish price monitoring.

```{r}

selectInput("species2", label = "Species:",
            choices = unique(supermarkets$Species_common_name), selected = "Atún")

```

Column
-----------------------------------------------------------------------

### Fish supermarkets prices

```{r}
renderPlot({
  supermarkets %>% 
          filter(Species_common_name == as.character(input$species2)) %>% 
          ggplot(aes(x = Month, y = Price)) +
          geom_point(col = "red") +
          geom_line(col = "red") +
          facet_wrap(~Species_common_name, scales = "free_y") +
          labs(x = "Month", y = "Price (MXN)", title = "Prices webscraped from supermarket webpages") +
          theme_lucid() +
          theme(strip.text = element_text(size = 17))
})
```

SNIIM
=====================================  

Column {.sidebar}
-----------------------------------------------------------------------

Fish price monitoring.

```{r}

selectInput("species3", label = "Species:",
            choices = unique(sniim$producto) %>% sort(.), selected = "Atún")

renderUI({
          selectInput("origin", label = "Origen:",
            choices = sniim %>% filter(producto == as.character(input$species3)) %>% select(origen) %>% unique() %>% pull() %>% sort(.), selected = "Baja California Sur")
})
```

Column
-----------------------------------------------------------------------

### Fish SNIIM

```{r}
renderPlot({
  sniim %>% 
          filter(producto == as.character(input$species3)) %>% 
          filter(origen == as.character(input$origin)) %>% 
          filter(type == "origin") %>% 
          mutate(fecha = as.Date(fecha)) %>% 
          ggplot(aes(x = fecha, y = pfrec)) +
          geom_point(col = "red") +
          geom_line(col = "red") +
          facet_wrap(~producto, scales = "free_y") +
          labs(x = "Fecha", y = "Price (MXN)", title = "Prices webscraped from SNIIM webpage") +
          scale_x_date(breaks = "1 day") +
          theme_lucid() +
          theme(strip.text = element_text(size = 17), 
                axis.text.x = element_text(angle = 90))
})
```
